/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface1: 'var(--surface-1)',
        surface2: 'var(--surface-2)',
        textPrimary: 'var(--text-primary)',
        textSecondary: 'var(--text-secondary)',
        textMuted: 'var(--text-muted)',
        border: 'var(--border)',
        accent: 'var(--fill-accent)',
        onAccent: 'var(--on-accent)',
        bgAccent: 'var(--bg-accent)',
        textAccent: 'var(--text-accent)',
        success: 'var(--text-success)',
        danger: 'var(--text-danger)',
        bgSuccess: 'var(--bg-success)',
        bgDanger: 'var(--bg-danger)',
        surface3: 'var(--surface-3)',
        nav: 'var(--nav-bg)',
        navBorder: 'var(--nav-border)',
        navText: 'var(--nav-text)',
        navTextHover: 'var(--nav-text-hover)',
        navHover: 'var(--nav-hover-bg)',
        navActive: 'var(--nav-active-bg)',
        dropdownBg: 'var(--dropdown-bg)',
        financial: 'var(--fill-financial)',
        onFinancial: 'var(--on-financial)',
        textFinancial: 'var(--text-financial)',
      },
    },
  },
  plugins: [],
};
